### ISSUE TITLE
GK feedback

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/guide-mongodb-intro#40]
- [x] update both short descriptions
  - "Learn how to store data ..." -> "Learn how to access and persist data ..."
- [x] need to add SEO title and description
- **Configuring the Open Liberty Server**
  - [x] `mpConfig-1.2` -> `mpConfig-1.4`
  - [x] "...an id of..." -> "...an `id` of..."
  - [ ] "... the password of mongodb..." Should/can the password be encrypted?
- **Implementing CRUD operations**
  - **Read**
    - [x] "...the `Try what you’ll build` section." remove the backticks
  - **Delete**
    - [x] `MongoCollection.DeleteOne()` -> `MongoCollection.deleteOne()`
    - [x] "containing the `object id`" but the code use `docId`. Should be consistent?  And need hotspot

**Comment by jimmy1wu** [comment]
> "... the password of mongodb..." Should/can the password be encrypted?

we use plaintext passwords for the keystore in other guides such as social login.
it _can_ be done, but the flow would be strange because we would need to explain how we did it and we do not start up the liberty server in the start folder til later on in the guide

rest of the feedback is addressed and the changes are available on lgdev site
